version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: webhookdb
      POSTGRES_USER: webhook
      POSTGRES_PASSWORD: webhookpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://webhook:webhookpass@db:5432/webhookdb
      REDIS_URL: redis://redis:6379/0
      PORT: "8000"
    ports:
      - "8000:8000"

  worker:
    build: .
    command: ["/bin/sh", "-c", "./start-worker.sh"]
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://webhook:webhookpass@db:5432/webhookdb
      REDIS_URL: redis://redis:6379/0

volumes:
  db_data:
